"use client"
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import 'devicon/devicon.min.css'
import {
    Sheet,
    SheetContent,
    SheetDescription,
    SheetHeader,
    SheetTitle,
    SheetTrigger,
} from "@/components/ui/sheet"
import {useRouter} from "next/navigation";

const ibm = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["100","200","300","400","500"],
})

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const router = useRouter();
    const handleGoToHome = () => {router.push("/home");};
    const handleGoToAbout = () => {router.push("/about");};
    const handleGoToContact = () => {router.push("/contact");};
    const handleGoToProjects = () => {router.push("/projects");};
    const handleGoToServices = () => {router.push("/services");};

  return (
    <html lang="en">

      <body
        className={`${ibm.className} antialiased`}
      >
        <div className={'hidden lg:block lg:flex'}>

            <div className={'flex-1 min-w-0 overflow-y-scroll'}>
                {children}
            </div>
        </div>

        <div className={'lg:hidden'}>
            <div className={'bg-transparent w-full h-[60px] p-[10px] flex justify-between items-center'}>
                <div className={'size-[50px] rounded-full bg-black'}></div>
                <Sheet>
                    <SheetTrigger>
                        <div className={'size-[50px] rounded-full border border-2 border-black flex items-center'}>
                            <span></span>
                        </div>
                    </SheetTrigger>
                    <SheetContent className={'bg-[#141313]'}>
                        <SheetTitle/>
                        <div className={'relative flex flex-col h-full text-white'}>
                            <ul className={'flex flex-col text-[20px] gap-[20px] text-center items-center'}>
                                <button onClick={handleGoToHome} className={'w-fit'}><li>HOME</li></button>
                                <button onClick={handleGoToAbout} className={'w-fit'}><li>ABOUT</li></button>
                                <button onClick={handleGoToServices} className={'w-fit'}><li>SERVICES</li></button>
                                <button onClick={handleGoToProjects} className={'w-fit'}><li>WORKS</li></button>
                                <button onClick={handleGoToContact} className={'w-fit'}><li>CONTACT</li></button>
                            </ul>
                            <div className={'absolute bottom-[20px] text-center w-full'}>
                                <span>Copyright ©2024 Fawzi Sayed. All right reserved.</span>
                            </div>
                        </div>
                    </SheetContent>
                </Sheet>
            </div>
            <div>
                {children}
            </div>
        </div>

      </body>
    </html>
  );
}
