import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import 'devicon/devicon.min.css'
import {
    Sheet,
    SheetContent,
    SheetDescription,
    SheetHeader,
    SheetTitle,
    SheetTrigger,
} from "@/components/ui/sheet"

const ibm = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["100","200","300","400","500"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${ibm.className} antialiased`}
      >
        <div className={'hidden lg:block lg:flex'}>
            <div className={'fixed flex flex-col bg-[#141313] w-[20%] shrink-0 h-screen sticky top-0 p-[40px] justify-between text-white'}>
                <div className={'size-[50px] rounded-full bg-white'}></div>
                <div>
                    <ul className={'flex flex-col text-[20px] gap-[20px]'}>
                        <li>HOME</li>
                        <li>ABOUT</li>
                        <li>SERVICES</li>
                        <li>WORKS</li>
                        <li>CONTACT</li>
                    </ul>
                </div>
                <div>
                    <span>Copyright ©2024 Fawzi Sayed. All right reserved.</span>
                </div>
            </div>
            <div className={'flex-1 min-w-0 overflow-y-scroll'}>
                {children}
            </div>
        </div>

        <div className={'lg:hidden'}>
            <div className={'bg-transparent w-full h-[60px] p-[10px] flex justify-between items-center'}>
                <span>LOGO</span>
                <Sheet>
                    <SheetTrigger>Open</SheetTrigger>
                    <SheetContent className={'bg-[#141313]'}>
                        <SheetTitle/>
                        <div className={'relative flex flex-col h-full text-white'}>
                            <ul className={'flex flex-col text-[20px] gap-[20px] text-center items-center'}>
                                <li>HOME</li>
                                <li>ABOUT</li>
                                <li>SERVICES</li>
                                <li>WORKS</li>
                                <li>CONTACT</li>
                            </ul>
                            <div className={'absolute bottom-[20px] text-center w-full'}>
                                <span>Copyright ©2024 Fawzi Sayed. All right reserved.</span>
                            </div>
                        </div>
                    </SheetContent>
                </Sheet>
            </div>
            <div>
                {children}
            </div>
        </div>

      </body>
    </html>
  );
}
